export {default as Home} from './Home/Home'
export {default as Destination} from './Destination/Destination'
export {default as DestinationMoon} from './DestinationList/DestinationMoon'
export {default as DestinationMars} from './DestinationList/DestinationMars'
export {default as DestinationEuropa} from './DestinationList/DestinationEuropa'
export {default as DestinationTitan} from './DestinationList/DestinationTitan'
export {default as Crew} from './Crew/Crew'
export {default as Technology} from './Technology/Technology'